// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zyrix-game/RefinedNeon.tsx": () => import("../components/mockups/zyrix-game/RefinedNeon.tsx")
};
